version: "3.8"
services:
  hardhat-node:
    image: node:18-alpine
    container_name: hardhat-node
    ports:
      - '8545:8545'
    command: |
      sh -c '
        mkdir /app &&
        cd /app &&
        npm init -y &&
        npm install hardhat &&
        echo "module.exports = {solidity: \"0.8.20\"};" > hardhat.config.js &&
        npx hardhat node
      '